import{it,expect,vi}from'vitest';
import{CaptureSession}from'../extension/capture-session';
import{playback}from'./fixtures';
function setup(){const sent:any[]=[],messages:any[]=[];const api={runtime:{getContexts:async()=>[],sendMessage:vi.fn(async(m:any)=>{messages.push(m);return{ok:true};})},tabs:{query:vi.fn(async()=>[{id:1,url:'https://www.youtube.com/watch?v=abcdefghijk'}]),sendMessage:vi.fn(async()=>({playback:playback({isolatedAudio:true}),capturedAt:Date.now()}))},offscreen:{createDocument:vi.fn(async()=>{}),closeDocument:vi.fn(async()=>{})},tabCapture:{getMediaStreamId:vi.fn(async()=> 'synthetic-stream')}};const c=new CaptureSession(m=>sent.push(m),api as any);c.ready(true);return{c,api,sent,messages};}
it('requires explicit session enabling and uses only a YouTube target tab',async()=>{const{c,api,sent}=setup();expect(api.tabCapture.getMediaStreamId).not.toHaveBeenCalled();await c.enable();expect(api.tabCapture.getMediaStreamId).toHaveBeenCalledWith({targetTabId:1});expect(c.tab).toBe(1);expect(sent.at(-1)).toMatchObject({type:'capture-state',active:true});await c.stop();expect(c.tab).toBeNull();expect(api.offscreen.closeDocument).toHaveBeenCalled();});
it('refuses capture on an old desktop or unrelated tab',async()=>{const{c,api}=setup();c.ready(false);await expect(c.enable()).rejects.toThrow('Update');c.ready(true);api.tabs.query.mockResolvedValue([{id:1,url:'https://example.com'}]);await expect(c.enable()).rejects.toThrow('YouTube');expect(api.tabCapture.getMediaStreamId).not.toHaveBeenCalled();});
it('does not transfer invocation permission to a different tab',async()=>{const{c,sent,messages}=setup();await c.enable();c.playback(1,'document1',playback({isolatedAudio:true}));await c.fromDesktop({type:'capture-request',id:'request01',tab:2,document:'document1',video:'abcdefghijk',generation:1});expect(sent.at(-1)).toMatchObject({type:'capture-error'});expect(messages.some(m=>m.type==='sample')).toBe(false);await c.stop();});
it('discards source changes and rejects unsolicited offscreen samples',async()=>{const{c,sent}=setup();await c.enable();c.playback(1,'document1',playback({isolatedAudio:true}));await c.fromDesktop({type:'capture-request',id:'request01',tab:1,document:'document1',video:'abcdefghijk',generation:1});c.playback(1,'document1',playback({isolatedAudio:true,seeking:true}));expect(sent.at(-1)).toMatchObject({type:'capture-error'});expect(await c.fromOffscreen({type:'capture-result-chunk',id:'request01',index:0,data:'AAAA'})).toEqual({ok:false});await c.stop();});
it('releases capture resources after stream creation failure',async()=>{const{c,api}=setup();api.tabCapture.getMediaStreamId.mockRejectedValue(Error('unavailable'));await expect(c.enable()).rejects.toThrow('Could not start');expect(c.tab).toBeNull();expect(api.offscreen.closeDocument).toHaveBeenCalled();});
