import{describe,it,expect,vi}from'vitest';
import{Controller}from'../desktop/controller';
import type{Store}from'../desktop/store';
import type{Provider}from'../desktop/provider';
import{settings}from'../shared/settings';
import{playback,lyric}from'./fixtures';
function setup(search:Provider['search']){const mappings:Store['data']['mappings']={};const store={data:{settings:settings({}),mappings},delay:(id:string)=>{const m=mappings[id];return m?.delays[String(m.record.id)]??0;},setDelay:(id:string,value:number)=>{const m=mappings[id];if(m)m.delays[String(m.record.id)]=value;},attach:(id:string,record:typeof lyric)=>{mappings[id]={record,delays:{},used:0};}} as unknown as Store;let now=0;const controller=new Controller(store,{search} as Provider,()=>{},()=>now,0);return{controller,store,setTime:(n:number)=>now=n};}
const snapshot=(patch:Parameters<typeof playback>[0]={})=>({v:1 as const,type:'snapshot' as const,tab:1,document:'document1',playback:playback(patch)});
describe('connected application lyric state',()=>{
 it('quarantines incompatible saved timing instead of displaying it as synchronized',()=>{const{controller:c,store}=setup(async()=>[]);store.data.mappings.abcdefghijk={record:{...lyric,duration:275,syncedLyrics:'[01:05.95]Synthetic start\n[05:05.78]Synthetic end'},delays:{},used:0};c.message('c','instance1',snapshot({duration:275,position:171}));expect(c.view().timingWarning).toContain('31 seconds');expect(c.view().ledger.synced).toBe(false);expect(c.view().current).toBe('');expect(c.record).not.toBeNull();});
 it('measures a per-record correction from a chosen line and paused media position',()=>{const{controller:c}=setup(async()=>[]);c.message('c','instance1',snapshot({duration:275,position:100,playing:false}));c.choose({...lyric,duration:275,syncedLyrics:'[01:05.95]Synthetic start\n[02:20]The line beginning now\n[05:05.78]Synthetic end'});expect(c.view().ledger.synced).toBe(false);expect(c.align(lyric.id,1)).toBe(-40000);expect(c.view()).toMatchObject({delay:-40000,current:'The line beginning now',timingWarning:undefined});expect(c.view().ledger.synced).toBe(true);});
 it('accounts for playback rate when aligning and rejects stale, ad or replaced selections',()=>{const{controller:c,setTime}=setup(async()=>[]);c.message('c','instance1',snapshot({position:10,rate:2}));c.choose(lyric);setTime(1000);expect(c.align(lyric.id,0)).toBe(2000);expect(()=>c.align(999,0)).toThrow('changed');expect(()=>c.align(lyric.id,999)).toThrow('changed');setTime(13000);expect(()=>c.align(lyric.id,0)).toThrow('fresh');c.message('c','instance1',snapshot({seq:2,ad:'ad'}));expect(()=>c.align(lyric.id,0)).toThrow('fresh');});
 it('publishes a paused clock and suppresses ledger lines during ads or stale playback',async()=>{const{controller:c,setTime}=setup(async()=>[lyric]);c.message('c','instance1',snapshot());await Promise.resolve();expect(c.view().ledger).toMatchObject({currentIndex:0,synced:true,clock:{advancing:true,position:10,lineStart:10,lineEnd:20}});c.message('c','instance1',snapshot({seq:2,playing:false}));expect(c.view().ledger.clock.advancing).toBe(false);c.message('c','instance1',snapshot({seq:3,ad:'ad'}));expect(c.view().ledger.synced).toBe(false);expect(c.view().ledger.lines.every(l=>!l.text)).toBe(true);c.message('c','instance1',snapshot({seq:4}));setTime(13000);expect(c.view().ledger.synced).toBe(false);expect(c.view().ledger.clock.advancing).toBe(false);});
 it('looks up a clean track title for YouTube 4K official music videos',async()=>{const search=vi.fn(async()=>[lyric]);const{controller:c}=setup(search);c.message('c','instance1',snapshot({title:'Test Ensemble - Paper Satellites (4K Official Music Video)'}));await Promise.resolve();expect(search.mock.calls[0].slice(0,3)).toEqual(['Paper Satellites','Test Ensemble',false]);expect(c.record?.id).toBe(1);expect(c.view().current).toBe('Paper lights across the ceiling');});
 it('looks up once per metadata identity, not on position ticks',async()=>{const search=vi.fn(async()=>[lyric]);const {controller:c}=setup(search);c.message('connection','instance1',snapshot());await Promise.resolve();c.message('connection','instance1',snapshot({seq:2,position:11}));expect(search).toHaveBeenCalledTimes(1);expect(c.view().current).toBe('Paper lights across the ceiling');});
 it('discards a late previous video response even if provider ignores cancellation',async()=>{let old!:(r:typeof lyric[])=>void;let count=0;const{controller:c}=setup(()=>++count===1?new Promise(r=>old=r):Promise.resolve([]));c.message('c','instance1',snapshot());c.message('c','instance1',snapshot({videoId:'lmnopqrstuv',generation:2,title:'Another Song'}));await Promise.resolve();old([lyric]);await Promise.resolve();expect(c.video).toBe('lmnopqrstuv');expect(c.record).toBeNull();expect(c.view().current).toBe('');});
 it('suppresses ads and resumes from fresh content clock',async()=>{const{controller:c}=setup(async()=>[lyric]);c.message('c','instance1',snapshot());await Promise.resolve();c.message('c','instance1',snapshot({seq:2,ad:'ad',position:0}));expect(c.view()).toMatchObject({current:'',status:'Advertisement — lyrics suspended'});c.message('c','instance1',snapshot({seq:3,ad:'uncertain',position:0}));expect(c.view().current).toBe('');c.message('c','instance1',snapshot({seq:4,position:20}));expect(c.view().current).toBe('Little shadows drift away');});
 it('clears after disconnect and suppresses stale snapshots',async()=>{const{controller:c,setTime}=setup(async()=>[lyric]);c.message('c','instance1',snapshot());await Promise.resolve();setTime(13000);expect(c.view().current).toBe('');expect(c.view().status).toContain('stale');c.disconnect('c');expect(c.view().videoId).toBeNull();expect(c.view().current).toBe('');});
 it('does not apply a delayed auto lookup over a manual import',async()=>{let resolve!:(r:typeof lyric[])=>void;const{controller:c}=setup(()=>new Promise(r=>resolve=r));c.message('c','instance1',snapshot());c.choose({...lyric,id:2,trackName:'Imported'});resolve([lyric]);await Promise.resolve();expect(c.record?.id).toBe(2);});
 it('uses instrumental and untimed states without fabricating synchronized lines',()=>{const{controller:c}=setup(async()=>[]);c.message('c','instance1',snapshot());c.choose({...lyric,instrumental:true,syncedLyrics:null});expect(c.view().status).toBe('Instrumental');c.choose({...lyric,syncedLyrics:null,plainLyrics:'Synthetic plain verse'});expect(c.view().current).toBe('');expect(c.view().status).toContain('Untimed');});
 it('keeps the content duration when an ad arrives during lookup',async()=>{let resolve!:(r:typeof lyric[])=>void;const{controller:c}=setup(()=>new Promise(r=>resolve=r));c.message('c','instance1',snapshot());c.message('c','instance1',snapshot({seq:2,ad:'ad',duration:15}));resolve([lyric]);await Promise.resolve();expect(c.record?.id).toBe(1);expect(c.view().current).toBe('');});
 it('publishes candidate summaries rather than full synchronized lyric bodies',async()=>{const{controller:c}=setup(async()=>[lyric]);c.message('c','instance1',snapshot());await Promise.resolve();const v=c.view();expect(v.record).toMatchObject({id:1,hasSynced:true});expect(v.record).not.toHaveProperty('syncedLyrics');expect(v.candidates[0]).not.toHaveProperty('plainLyrics');});
});
