import{describe,it,expect}from'vitest';
import{parseLrc,selectLines,normalizeTitle,songQuery,confidentMatch,matchScore,recordTimingWarning,timelineOverrun,type RecordLyrics}from'../shared/lyrics';
export const record:RecordLyrics={id:1,trackName:'Paper Satellites',artistName:'Test Ensemble',albumName:'Synthetic Fixtures',duration:180,instrumental:false,plainLyrics:null,syncedLyrics:'[00:10.00]Paper lights across the ceiling\n[00:20.00]Little shadows drift away'};
describe('LRC and lyric timing',()=>{
 it('parses fractions, multi-tags, metadata, offsets and malformed lines deterministically',()=>{const p=parseLrc('[ti:Example]\n[offset:500]\n[00:02.3][00:03:250]Second\n[00:01.01]First\n[00:99.00]bad\n[garbage]\n[00:02.300]Translation\n[00:04]');expect(p.metadata.ti).toBe('Example');expect(p.lines).toEqual([{time:.51,text:'First'},{time:1.8,text:'Second\nTranslation'},{time:2.75,text:'Second'},{time:3.5,text:''}]);});
 it('handles negative embedded offsets, BOM and duplicate lines',()=>{expect(parseLrc('\uFEFF[offset:-1000]\n[00:01]One\n[00:01]One').lines).toEqual([{time:2,text:'One'}]);});
 it('selects before first, exact boundary, neighbors and ended neutral state',()=>{const l=parseLrc(record.syncedLyrics!).lines;expect(selectLines(l,9)).toMatchObject({index:-1,current:'',next:'Paper lights across the ceiling'});expect(selectLines(l,10)).toMatchObject({index:0,next:'Little shadows drift away'});expect(selectLines(l,20)).toMatchObject({index:1,previous:'Paper lights across the ceiling'});expect(selectLines(l,30,0,true).current).toBe('');});
 it('positive delay makes a 10-second lyric appear at 12, negative at 8',()=>{const l=parseLrc(record.syncedLyrics!).lines;expect(selectLines(l,11.99,2000).index).toBe(-1);expect(selectLines(l,12,2000).index).toBe(0);expect(selectLines(l,8,-2000).index).toBe(0);});
 it('preserves explicit empty instrumental gaps',()=>{expect(selectLines(parseLrc('[00:01]One\n[00:02]\n[00:05]Two').lines,3).current).toBe('');});
});
describe('conservative matching',()=>{
 it('rejects a matching-duration record whose lyric timeline belongs to a longer edit',()=>{const bad={...record,duration:275,syncedLyrics:'[01:05.95]Synthetic opening\n[05:05.78]Synthetic ending'};expect(recordTimingWarning(bad)).toContain('31 seconds');expect(confidentMatch({title:record.trackName,artist:record.artistName,duration:275},[bad])).toBeNull();});
 it('rejects timestamps past the video even when record metadata fits its own timeline',()=>{const extended={...record,duration:300,syncedLyrics:'[00:10]Opening\n[04:50]Ending'};expect(recordTimingWarning(extended)).toBeUndefined();expect(confidentMatch({title:record.trackName,artist:record.artistName,duration:275},[extended])).toBeNull();});
 it('uses content timestamps rather than empty trailing markers to assess an overrun',()=>{const lines=parseLrc('[00:10]Verse\n[03:00]End\n[05:00]').lines;expect(timelineOverrun(lines,180)).toBe(0);expect(timelineOverrun(lines,150,-30000)).toBe(0);});
 it.each(['4K Official Music Video','Official Music Video 4K','Official Video HD','HD / Official Audio','Official Lyric Video'])('cleans combined quality and media decorations: %s',decoration=>{expect(songQuery(`Test Ensemble - Paper Satellites (${decoration})`,'')).toEqual({title:'Paper Satellites',artist:'Test Ensemble'});});
 it('normalizes the reported YouTube title without changing its recording title',()=>{expect(songQuery('The Cranberries - Linger (4K Official Music Video)','')).toEqual({title:'Linger',artist:'The Cranberries'});});
 it('preserves meaningful parenthetical recording information and title punctuation',()=>{expect(normalizeTitle('Paper Satellites (Live Acoustic) [4K Official Music Video]')).toBe('Paper Satellites (Live Acoustic)');expect(normalizeTitle('Paper Satellites (2024 Remaster)')).toBe('Paper Satellites (2024 Remaster)');expect(normalizeTitle('Paper Satellites (Radio Edit)')).toBe('Paper Satellites (Radio Edit)');expect(normalizeTitle('A Song - A Story')).toBe('A Song - A Story');expect(normalizeTitle('Paper Satellites — 4K Official Music Video')).toBe('Paper Satellites');});
 it('removes decorations while retaining recording distinctions',()=>{expect(normalizeTitle('Paper Satellites (Live) [Official Video]')).toBe('Paper Satellites (Live)');expect(normalizeTitle('Paper Satellites (Acoustic Remix Cover)')).toContain('Acoustic Remix Cover');expect(songQuery('Test Ensemble - Paper Satellites (Lyrics)','')).toEqual({title:'Paper Satellites',artist:'Test Ensemble'});});
 it('accepts video intro/outro differences without duration equality',()=>{expect(confidentMatch({title:record.trackName,artist:record.artistName,duration:195},[record])).toBe(record);});
 it('refuses absent artists, different recordings, and ambiguous durations',()=>{expect(confidentMatch({title:record.trackName,artist:'',duration:180},[record])).toBeNull();expect(matchScore({title:'Paper Satellites (Live)',artist:record.artistName,duration:180},record)).toBe(0);expect(confidentMatch({title:record.trackName,artist:record.artistName,duration:187},[record,{...record,id:2,duration:194}])).toBeNull();});
 it('prefers synchronized equivalent album duplicates',()=>{expect(confidentMatch({title:record.trackName,artist:record.artistName,duration:180},[{...record,id:2,syncedLyrics:null},record])?.id).toBe(1);});
});
