import{afterEach,beforeEach,describe,it,expect,vi}from'vitest';
import{JSDOM}from'jsdom';
import{watchId,readMetadata,getVideo,adState,observeChanges,rememberContent,forgetContent}from'../extension/adapter';
import{sourceAllowsVideo,sourceUrl,canPinSource,SOURCE_PATTERNS}from'../shared/sources';
let dom:JSDOM;
const musicMarkup=(id='abcdefghijk')=>`<ytmusic-player video-id="${id}"><div id="movie_player"><video class="html5-main-video"></video></div></ytmusic-player><ytmusic-player-bar><yt-formatted-string class="title">Paper Satellites</yt-formatted-string><yt-formatted-string class="byline"><a href="/channel/UCsynthetic">Test Ensemble</a> • <a href="/browse/MPREalbum">Synthetic Album</a> • 2026</yt-formatted-string></ytmusic-player-bar>`;
beforeEach(()=>{dom=new JSDOM(musicMarkup(),{url:'https://music.youtube.com/watch?v=abcdefghijk'});vi.stubGlobal('document',dom.window.document);vi.stubGlobal('location',dom.window.location);vi.stubGlobal('MutationObserver',dom.window.MutationObserver);forgetContent();});
afterEach(()=>{dom.window.close();vi.unstubAllGlobals();forgetContent();});
describe('YouTube Music adapter with a synthetic DOM',()=>{
 it('reads the current regular watch container and media when an older container remains hidden',()=>{dom.reconfigure({url:'https://www.youtube.com/watch?v=lmnopqrstuv'});document.body.innerHTML='<ytd-watch-flexy video-id="abcdefghijk" hidden><ytd-watch-metadata><h1><yt-formatted-string>Old song</yt-formatted-string></h1></ytd-watch-metadata><div id="movie_player" class="ad-showing"><video id="old-video"></video></div></ytd-watch-flexy><ytd-watch-flexy video-id="lmnopqrstuv"><ytd-watch-metadata><h1><yt-formatted-string>New song</yt-formatted-string></h1></ytd-watch-metadata><div id="movie_player"><video id="new-video"></video></div></ytd-watch-flexy>';expect(readMetadata('lmnopqrstuv')).toMatchObject({title:'New song',identity:true});expect(getVideo()?.id).toBe('new-video');expect(adState()).toBe('content');});
 it('extracts the active music track and artist without mistaking the album for the artist',()=>{expect(watchId()).toBe('abcdefghijk');expect(readMetadata('abcdefghijk')).toEqual({title:'Paper Satellites',artist:'Test Ensemble',identity:true});expect(getVideo()?.tagName).toBe('VIDEO');});
 it('uses player identity when music continues on a browse/library page',()=>{dom.reconfigure({url:'https://music.youtube.com/library'});expect(watchId()).toBe('abcdefghijk');expect(readMetadata('abcdefghijk').identity).toBe(true);});
 it('retains only a confirmed unchanged track while browsing when no ID attribute is exposed',()=>{document.querySelector('ytmusic-player')!.removeAttribute('video-id');const meta=readMetadata('abcdefghijk');rememberContent('abcdefghijk',meta);dom.reconfigure({url:'https://music.youtube.com/browse/library'});expect(watchId()).toBe('abcdefghijk');expect(readMetadata('abcdefghijk').identity).toBe(true);document.querySelector('.title')!.textContent='Another Track';expect(watchId()).toBeNull();expect(readMetadata('abcdefghijk').identity).toBe(false);});
 it('does not associate old player metadata with a new watch URL',()=>{dom.reconfigure({url:'https://music.youtube.com/watch?v=lmnopqrstuv'});expect(watchId()).toBe('lmnopqrstuv');expect(readMetadata('lmnopqrstuv').identity).toBe(false);document.querySelector('ytmusic-player')!.setAttribute('video-id','lmnopqrstuv');document.querySelector('.title')!.textContent='Quiet City';expect(readMetadata('lmnopqrstuv')).toMatchObject({title:'Quiet City',identity:true});});
 it('detects ad states separately from content identity',()=>{document.querySelector('#movie_player')!.classList.add('ad-showing');expect(adState()).toBe('ad');document.querySelector('#movie_player')!.classList.remove('ad-showing');expect(adState()).toBe('content');});
 it('can use player links or YouTube thumbnail identity but rejects conflicting signals',()=>{document.querySelector('ytmusic-player')!.removeAttribute('video-id');dom.reconfigure({url:'https://music.youtube.com/'});document.querySelector('ytmusic-player')!.insertAdjacentHTML('beforeend','<a class="ytp-title-link" href="https://www.youtube.com/watch?v=abcdefghijk">Track</a>');expect(watchId()).toBe('abcdefghijk');document.querySelector('ytmusic-player-bar')!.insertAdjacentHTML('beforeend','<img src="https://i.ytimg.com/vi/lmnopqrstuv/hqdefault.jpg">');expect(watchId()).toBeNull();expect(readMetadata('abcdefghijk').identity).toBe(false);});
 it('ignores malformed links and obtains artist text from a plain byline',()=>{document.querySelector('ytmusic-player')!.insertAdjacentHTML('beforeend','<a class="ytp-title-link" href="http://[">Bad link</a>');document.querySelector('.byline')!.textContent='Test Ensemble • Synthetic Album • 2026';expect(readMetadata('abcdefghijk')).toMatchObject({artist:'Test Ensemble',identity:true});});
 it('preserves regular YouTube detection and never equates an uploader with an artist',()=>{dom.reconfigure({url:'https://www.youtube.com/watch?v=abcdefghijk'});document.body.innerHTML='<ytd-watch-flexy video-id="abcdefghijk"><ytd-watch-metadata><h1><yt-formatted-string>Test Ensemble - Paper Satellites</yt-formatted-string></h1></ytd-watch-metadata><div id="owner">Some uploader</div></ytd-watch-flexy><div id="movie_player"><video class="html5-main-video"></video></div>';expect(watchId()).toBe('abcdefghijk');expect(readMetadata('abcdefghijk')).toMatchObject({artist:'',identity:true});});
 it('cleans up DOM observers after use',async()=>{let changes=0;const stop=observeChanges(()=>changes++);document.querySelector('.title')!.textContent='New title';await Promise.resolve();expect(changes).toBeGreaterThan(0);stop();const count=changes;document.querySelector('.title')!.textContent='Later title';await Promise.resolve();expect(changes).toBe(count);});
});
describe('source routing at the service worker boundary',()=>{
 it('limits source discovery to the two supported YouTube hosts',()=>{expect(SOURCE_PATTERNS).toEqual(['https://www.youtube.com/*','https://music.youtube.com/*']);expect(sourceAllowsVideo('https://music.youtube.com/watch?v=abcdefghijk','abcdefghijk')).toBe(true);expect(sourceAllowsVideo('https://music.youtube.com/library','abcdefghijk')).toBe(true);expect(sourceAllowsVideo('https://www.youtube.com/','abcdefghijk')).toBe(false);expect(canPinSource('https://music.youtube.com/library')).toBe(true);});
 it.each(['http://music.youtube.com/watch?v=abcdefghijk','https://music.youtube.com.evil.example/watch?v=abcdefghijk','https://evil.example/','https://music.youtube.com:9999/','https://name:password@music.youtube.com/'])('rejects unrelated or malformed source URLs %s',url=>{expect(sourceUrl(url)).toBeNull();expect(sourceAllowsVideo(url,'abcdefghijk')).toBe(false);});
 it('rejects a replaced track ID on a watch page',()=>{expect(sourceAllowsVideo('https://music.youtube.com/watch?v=lmnopqrstuv','abcdefghijk')).toBe(false);expect(sourceAllowsVideo('https://music.youtube.com/watch','abcdefghijk')).toBe(false);});
});
