import{describe,it,expect,vi,afterEach}from'vitest';
import{Provider}from'../desktop/provider';
import{lyric}from'./fixtures';
const cache=()=>{const m=new Map<string,typeof lyric[]>();return{cacheGet:(k:string)=>m.get(k),cachePut:(k:string,v:typeof lyric[])=>m.set(k,v)};};
afterEach(()=>vi.useRealTimers());
describe('LRCLIB requests with mocked network',()=>{
 it('uses encoded metadata, deduplicates requests and caches successful results',async()=>{const calls:URL[]=[];const provider=new Provider(cache(),async url=>{calls.push(new URL(String(url)));return new Response(JSON.stringify([lyric]));});const[a,b]=await Promise.all([provider.search('Paper & Satellites','Test Ensemble'),provider.search('Paper & Satellites','Test Ensemble')]);expect(a).toEqual(b);expect(calls).toHaveLength(1);expect(calls[0].searchParams.get('track_name')).toBe('Paper & Satellites');expect(await provider.search('Paper & Satellites','Test Ensemble')).toEqual([lyric]);expect(calls).toHaveLength(1);});
 it('exposes rate limiting and prevents retry before Retry-After',async()=>{let now=0,calls=0;const p=new Provider(cache(),async()=>{calls++;return new Response('',{status:429,headers:{'Retry-After':'90'}});},()=>now);await expect(p.search('one')).rejects.toThrow('rate limit');now=80000;await expect(p.search('two')).rejects.toThrow('rate limit');expect(calls).toBe(1);now=91000;await expect(p.search('two')).rejects.toThrow('rate limit');expect(calls).toBe(2);});
 it.each([JSON.stringify([{...lyric,duration:'bad'}]),'{}','not json'])('rejects malformed responses %s',async body=>{const p=new Provider(cache(),async()=>new Response(body));await expect(p.search('song')).rejects.toThrow();});
 it('times out and supports explicit cancellation',async()=>{vi.useFakeTimers();const fetcher:typeof fetch=async(_url,options)=>new Promise((_r,reject)=>options?.signal?.addEventListener('abort',()=>reject(Error('aborted'))));const p=new Provider(cache(),fetcher);const pending=expect(p.search('one')).rejects.toThrow('timed out');await vi.advanceTimersByTimeAsync(10000);await pending;const controller=new AbortController();const canceled=expect(p.search('two','',false,controller.signal)).rejects.toThrow('canceled');controller.abort();await canceled;});
 it('rejects oversized responses',async()=>{const p=new Provider(cache(),async()=>new Response('x'.repeat(4_000_001)));await expect(p.search('song')).rejects.toThrow('size limit');});
 it('starts fresh work rather than reusing a canceled request after reconnect',async()=>{let calls=0;const p=new Provider(cache(),async(_url,options)=>{if(++calls===1)return new Promise((_resolve,reject)=>options?.signal?.addEventListener('abort',()=>reject(Error('abort'))));return new Response(JSON.stringify([lyric]));});const abort=new AbortController();const old=expect(p.search('song','',false,abort.signal)).rejects.toThrow('canceled');abort.abort();const fresh=p.search('song');await old;expect(await fresh).toEqual([lyric]);expect(calls).toBe(2);});
});

it('honors HTTP-date Retry-After and does not negative-cache transport failures',async()=>{let now=Date.parse('2026-01-01T00:00:00Z');const c=cache(),put=vi.spyOn(c,'cachePut');let calls=0;const p=new Provider(c,async()=>{calls++;return new Response('',{status:429,headers:{'Retry-After':'Thu, 01 Jan 2026 00:05:00 GMT'}});},()=>now);await expect(p.search('date')).rejects.toThrow('rate limit');now+=120000;await expect(p.search('date')).rejects.toThrow('rate limit');expect(calls).toBe(1);expect(put).not.toHaveBeenCalled();});
it('retains all bounded valid candidates and negative-caches only successful empty responses',async()=>{const c=cache();const p=new Provider(c,async()=>new Response(JSON.stringify(Array.from({length:30},(_,i)=>({...lyric,id:i})))));expect(await p.search('many')).toHaveLength(30);const empty=new Provider(c,async()=>new Response('[]'));expect(await empty.search('empty')).toEqual([]);expect(c.cacheGet('track_name=empty')).toEqual([]);});
it('uses exact lookup only with genuine album, artist, title and finite duration',async()=>{const request=vi.fn(async()=>new Response(JSON.stringify(lyric)));const p=new Provider(cache(),request);expect(await p.exact('title','artist','',180)).toEqual([]);expect(request).not.toHaveBeenCalled();expect(await p.exact('title','artist','album',180)).toEqual([lyric]);expect(String(request.mock.calls[0][0])).toContain('/api/get?');});
