import {describe,it,expect,vi} from 'vitest';
import {Controller} from '../desktop/controller';
import {ProviderError} from '../desktop/provider';
import {playback,lyric} from './fixtures';
import {settings} from '../shared/settings';
import type {Store} from '../desktop/store';
import type {Provider} from '../desktop/provider';
function setup(search:Provider['search'],settle=0){let time=0;const data={settings:settings({}),mappings:{},rejected:{}} as Store['data'];const store={data,rejects:(id:string)=>data.rejected[id]?.ids??[],attach:vi.fn((id:string,record:any,provenance:any,evidence:any)=>{data.mappings[id]={record,provenance,evidence,matcherVersion:2,delays:data.mappings[id]?.delays??{},used:0};}),delay:(id:string)=>data.mappings[id]?.delays[String(data.mappings[id].record.id)]??0,reject:(id:string,n:number)=>{data.rejected[id]={ids:[n],used:0};},forget:(id:string)=>{const r=data.mappings[id];if(r)data.rejected[id]={ids:[r.record.id],used:0};delete data.mappings[id];}} as unknown as Store;const c=new Controller(store,{search} as Provider,()=>{},()=>time,settle);const send=(patch:Parameters<typeof playback>[0]={},tab=1,document='document1')=>c.message('connection','instance1',{v:1,type:'snapshot',tab,document,playback:playback(patch)});return{c,store,send,time:(n:number)=>time=n};}
const flush=async()=>{for(let n=0;n<20;n++)await Promise.resolve();};
describe('bounded metadata resolution',()=>{
 it('reproduces the missing duration failure and reranks a short-title candidate without fetching again',async()=>{const search=vi.fn(async()=>[{...lyric,trackName:'Home'}]);const{c,send}=setup(search);send({title:'Home',artist:lyric.artistName,duration:null,provenance:'structured'});await flush();expect(c.record).toBeNull();const count=search.mock.calls.length;send({seq:2,title:'Home',artist:lyric.artistName,duration:180,provenance:'structured'});await flush();expect(c.record?.trackName).toBe('Home');expect(search).toHaveBeenCalledTimes(count);});
 it('scores an in-flight response against new artist evidence',async()=>{let resolve!:(r:any[])=>void;const search=vi.fn(()=>new Promise<any[]>(r=>resolve=r));const{c,send}=setup(search);send({title:lyric.trackName,artist:''});send({seq:2,title:lyric.trackName,artist:'Other Ensemble'});resolve([lyric]);await flush();expect(c.record).toBeNull();expect(c.trace.some(t=>t.candidates?.some(r=>r.conflicts.includes('artist-conflict')))).toBe(true);c.close();});
 it('rescues a failure through a distinct bounded hypothesis',async()=>{const search=vi.fn(async(_t,_a,free)=>free?[lyric]:[]);const{c,send}=setup(search);send();await flush();expect(c.record?.id).toBe(1);expect(search.mock.calls.length).toBeLessThanOrEqual(6);expect(c.status).not.toContain('Choose');});
 it('ranks the correct candidate beyond provider position twenty',async()=>{const{c,send}=setup(async()=>[...Array.from({length:24},(_,i)=>({...lyric,id:i+2,artistName:'Other'})),lyric]);send();await flush();expect(c.record?.id).toBe(1);expect(c.candidates).toHaveLength(20);expect(c.candidates[0].id).toBe(1);});
 it('bounds a churn episode and ignores whitespace / duration jitter heartbeats',async()=>{const search=vi.fn(async()=>[]);const{c,send}=setup(search);send();await flush();const n=search.mock.calls.length;for(let i=2;i<25;i++){send({seq:i,title:i<5?'Test Ensemble  -  Paper Satellites':`Test Ensemble - Song ${i}`,duration:180.04});await flush();}expect(search.mock.calls.length).toBeLessThanOrEqual(6);expect(n).toBeLessThan(6);c.close();});
 it('settles metadata bursts before searching',async()=>{vi.useFakeTimers();try{const search=vi.fn(async()=>[lyric]);const{c,send}=setup(search,400);send({title:'Transient'});send({seq:2});expect(search).not.toHaveBeenCalled();await vi.advanceTimersByTimeAsync(400);expect(search.mock.calls[0][0]).toBe(lyric.trackName);c.close();}finally{vi.useRealTimers();}});
 it('does not resurrect a forgotten or explicitly replaced automatic result',async()=>{let resolve!:(r:any[])=>void;const{c,store,send}=setup(()=>new Promise(r=>resolve=r));send();c.choose({...lyric,id:9});resolve([lyric]);await flush();expect(c.record?.id).toBe(9);c.forget();expect(store.rejects('abcdefghijk')).toContain(9);c.retry();await flush();expect(c.record).toBeNull();c.close();});
 it('retains manual provenance and gives old unknown selections no confirmation claim',()=>{const{c,store,send}=setup(async()=>[]);store.data.mappings.abcdefghijk={record:lyric,used:0,delays:{'1':1200},provenance:'legacy-unknown'};send();expect(c.record?.id).toBe(1);expect(c.view().matchProvenance).toBe('legacy-unknown');send({seq:2,title:'Other - Different Song'});expect(c.view().ledger.synced).toBe(false);expect(c.record?.id).toBe(1);c.close();});
 it('reuses strongly supported recording knowledge without copying video alignment',async()=>{const{c,store,send}=setup(async()=>[]);store.data.mappings.lmnopqrstuv={record:lyric,used:0,delays:{'1':12000},matcherVersion:2,provenance:'explicit-selection'};send();await flush();expect(c.record?.id).toBe(1);expect(c.view().delay).toBe(0);});
 it('stops on temporary failure, recovers only on explicit retry, and never opens settings',async()=>{let offline=true;const search=vi.fn(async()=>{if(offline)throw new ProviderError('offline','offline');return[lyric];});const{c,send}=setup(search);send();await flush();expect(c.status).toBe('Lyrics temporarily unavailable');send({seq:2});await flush();expect(search).toHaveBeenCalledTimes(1);offline=false;c.retry();await flush();expect(c.record?.id).toBe(1);});
 it('cancels old documents and source changes even when network cancellation is ignored',async()=>{let resolve!:(r:any[])=>void;let calls=0;const{c,send}=setup(()=>++calls===1?new Promise(r=>resolve=r):Promise.resolve([]));send();send({generation:2,title:'Different Song'},1,'document2');resolve([lyric]);await flush();expect(c.record).toBeNull();expect(c.view().current).toBe('');});
});
it('retries a transient failure once after cooldown on fresh playback without resetting its request budget',async()=>{let offline=true;const search=vi.fn(async()=>{if(offline)throw new ProviderError('offline','offline');return[lyric];});const{c,send,time}=setup(search);send();await flush();time(31000);offline=false;send({seq:2,position:41});await flush();expect(c.record?.id).toBe(1);expect(search).toHaveBeenCalledTimes(2);expect(c.trace.some(t=>t.requests===2)).toBe(true);});
it('holds a saved absolute manual correction through metadata improvement and automatic recognition',async()=>{const{c,store,send}=setup(async()=>[{...lyric,id:2}]);store.data.mappings.abcdefghijk={record:lyric,used:0,delays:{'1':12000},matcherVersion:2,provenance:'metadata'};send({duration:192});await flush();expect(c.record?.id).toBe(1);expect(c.hasManualTiming()).toBe(true);expect(c.canRecognize()).toBe(false);send({seq:2,duration:195});expect(c.record?.id).toBe(1);expect(c.view().delay).toBe(12000);});
