import{describe,it,expect}from'vitest';
import{settings,resolvedTheme,shouldShowOverlay}from'../shared/settings';
import{configureStartup,loginItemOptions}from'../desktop/startup';
import{previewState,previewScale}from'../shared/preview';
import type{ViewState}from'../shared/ui';
describe('settings preferences and preview',()=>{
 it('resolves System against the OS while explicit themes remain fixed',()=>{expect(resolvedTheme(settings({theme:'system'}),true)).toBe('dark');expect(resolvedTheme(settings({theme:'system'}),false)).toBe('light');expect(resolvedTheme(settings({theme:'dark'}),false)).toBe('dark');});
 it('uses the new width and font ranges and migrates older appearance choices',()=>{expect(settings({width:360,fontSize:14})).toMatchObject({width:360,fontSize:14});expect(settings({width:460,fontSize:28})).toMatchObject({width:460,fontSize:28});expect(settings({width:720,fontSize:42})).toMatchObject({width:460,fontSize:28});expect(settings({width:420})).toMatchObject({width:400});});
 it('shows only during playback when enabled while retaining manual visibility',()=>{expect(shouldShowOverlay(settings({onlyWhilePlaying:true}),false)).toBe(false);expect(shouldShowOverlay(settings({onlyWhilePlaying:true}),true)).toBe(true);expect(shouldShowOverlay(settings({visible:false,onlyWhilePlaying:true}),true)).toBe(false);expect(shouldShowOverlay(settings({}),false)).toBe(true);});
 it('builds correct native startup options for development and packaged Windows apps',()=>{expect(loginItemOptions(true,false,'C:/app/electron.exe','C:/My Project')).toEqual({openAtLogin:true,path:'C:/app/electron.exe',args:['"C:/My Project"'],name:'LyricGlass'});expect(loginItemOptions(false,true,'C:/app/LyricGlass.exe','ignored').args).toEqual([]);});
 it('applies startup preferences through the mocked native boundary and reports a failed change',()=>{let enabled=false;configureStartup({setLoginItemSettings:o=>{enabled=o.openAtLogin;},getLoginItemSettings:()=>({openAtLogin:enabled})},true,true,'C:/app.exe','');expect(enabled).toBe(true);expect(()=>configureStartup({setLoginItemSettings:()=>{},getLoginItemSettings:()=>({openAtLogin:false})},true,true,'C:/app.exe','')).toThrow('did not apply');});
 it('renders sample timestamps at the true selected width without changing real playback',()=>{const source={settings:settings({width:460,theme:'light',fontSize:24,karaoke:false}),videoId:'abcdefghijk',title:'A current video',artist:'Artist',delay:2000,ledger:{clock:{position:99}}}as ViewState;const preview=previewState(source,0);expect(preview.title).toBe(source.title);expect(preview.delay).toBe(2000);expect(preview.settings).toMatchObject({width:460,theme:'light',fontSize:24,karaoke:false});expect(preview.ledger.lines).toHaveLength(5);expect(preview.ledger.clock.words?.length).toBeGreaterThan(0);expect(previewState(source,7).current).not.toBe(preview.current);expect(source.ledger.clock.position).toBe(99);expect(previewScale(460)).toBeCloseTo(300/460);expect(previewScale(360)).toBe(.72);});
});
