// @vitest-environment jsdom
import{beforeEach,afterEach,it,expect,vi}from'vitest';
import{act,createElement}from'react';
import{createRoot,type Root}from'react-dom/client';
import{SettingsWindow}from'../desktop/renderer/SettingsWindow';
import{settings}from'../shared/settings';
import type{Command,ViewState}from'../shared/ui';
import{summarize}from'../shared/ui';
import{lyric}from'./fixtures';
import{previewState}from'../shared/preview';
let host:HTMLDivElement,root:Root,state:ViewState,commands:Command[],frames:Map<number,FrameRequestCallback>,nextFrame:number;
function render(){root.render(createElement(SettingsWindow,{state,act:dispatch,error:''}));}
async function dispatch(command:Command){commands.push(command);if(command.type==='settings')state={...state,settings:settings({...state.settings,...command.patch})};if(command.type==='delay')state={...state,delay:command.value};if(command.type==='resetTiming')state={...state,delay:0};if(command.type==='select')state={...state,record:state.candidates.find(r=>r.id===command.id)!};render();}
const button=(label:string)=>Array.from(host.querySelectorAll<HTMLButtonElement>('button')).find(b=>b.textContent===label)!;
const click=async(element:HTMLElement)=>{await act(async()=>element.click());};
beforeEach(async()=>{
  vi.stubGlobal('IS_REACT_ACT_ENVIRONMENT',true);vi.stubGlobal('matchMedia',()=>({matches:false}));vi.stubGlobal('ResizeObserver',class{observe(){}disconnect(){}});frames=new Map();nextFrame=0;
  vi.stubGlobal('requestAnimationFrame',(fn:FrameRequestCallback)=>{const id=++nextFrame;frames.set(id,fn);return id;});vi.stubGlobal('cancelAnimationFrame',(id:number)=>frames.delete(id));
  vi.spyOn(performance,'now').mockReturnValue(0);
  vi.stubGlobal('lyricglass',{command:vi.fn(async()=>({ok:true})),getTimingLines:async()=>({videoId:'abcdefghijk',recordId:1,lines:[]})});
  state=previewState({settings:settings({}),resolvedTheme:'light',connection:'Connected to browser',connectionBrowser:'Chrome',paired:true,videoId:'abcdefghijk',title:'Test Ensemble - Paper Satellites',artist:'Test Ensemble',delay:250,record:summarize(lyric),candidates:[summarize(lyric),summarize({...lyric,id:2,syncedLyrics:null,plainLyrics:'Synthetic plain text'})],warning:'',shortcuts:[]}as ViewState,0);
  commands=[];host=document.createElement('div');document.body.append(host);root=createRoot(host);await act(async()=>render());
});
afterEach(async()=>{await act(async()=>root.unmount());host.remove();vi.restoreAllMocks();vi.unstubAllGlobals();});
it('renders the three sections, custom titlebar, current match and independent sample preview',()=>{expect(Array.from(host.querySelectorAll('h2')).map(h=>h.textContent)).toEqual(['Connection','Appearance','Lyric match & timing']);expect(host.textContent).toContain('LyricGlass · Settings');expect(host.textContent).toContain('LIVE PREVIEW');expect(host.textContent).toContain('SAMPLE LYRICS');expect(host.querySelector('.preview-card-position')?.getAttribute('style')).toContain('width: 400px');expect(host.querySelector('select[aria-label="Width"]')).toBeNull();expect(host.querySelectorAll('input[type="checkbox"]')).toHaveLength(0);expect(window.lyricglass.command).not.toHaveBeenCalled();});
it('applies theme and width to the real preview card immediately',async()=>{await click(button('System'));expect(state.settings.theme).toBe('system');expect(host.querySelector('.preview-stage .ledger-card')?.getAttribute('data-theme')).toBe('light');await click(button('Wide · 460'));expect(state.settings.width).toBe(460);expect(host.querySelector('.preview-card-position')?.getAttribute('style')).toContain('width: 460px');expect(window.lyricglass.command).not.toHaveBeenCalled();});
it('updates text-only and karaoke preview states without moving the actual overlay',async()=>{await click(host.querySelector('[aria-label="Text only with shadow"]')!);expect(host.querySelector('.preview-stage .ledger-card')?.classList.contains('is-text-only')).toBe(true);await click(host.querySelector('[aria-label="Karaoke word highlight"]')!);expect(state.settings.karaoke).toBe(false);expect(host.querySelector('.preview-stage [data-word]')).toBeNull();expect(host.querySelector('.preview-stage .line-highlight')).not.toBeNull();expect(window.lyricglass.command).not.toHaveBeenCalled();});
it('routes startup and playing-only toggles through the validated settings API',async()=>{await click(host.querySelector('[aria-label="Launch at startup"]')!);expect(commands.at(-1)).toEqual({type:'settings',patch:{launchAtStartup:true}});await click(host.querySelector('[aria-label="Show widget only while a video is playing"]')!);expect(commands.at(-1)).toEqual({type:'settings',patch:{onlyWhilePlaying:true}});});
it('selects a result and retains search/import behavior',async()=>{await click(host.querySelectorAll<HTMLElement>('.settings-result')[1]);expect(state.record?.id).toBe(2);expect(host.querySelectorAll('.settings-result')[1].getAttribute('aria-pressed')).toBe('true');await click(button('Import .lrc'));expect(commands.at(-1)).toEqual({type:'import',videoId:'abcdefghijk'});const input=host.querySelector<HTMLInputElement>('#match-search')!;await act(async()=>{Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value')!.set!.call(input,'Synthetic artist song');input.dispatchEvent(new Event('input',{bubbles:true}));});await act(async()=>host.querySelector('form')!.dispatchEvent(new Event('submit',{bubbles:true,cancelable:true})));expect(commands.at(-1)).toEqual({type:'search',videoId:'abcdefghijk',query:'Synthetic artist song'});});
it('uses the compact per-video stepper and native window actions',async()=>{await click(host.querySelector('[aria-label="Lyrics later by 250 milliseconds"]')!);expect(state.delay).toBe(500);expect(host.querySelector('.settings-stepper output')?.textContent).toBe('+500 ms');await click(host.querySelector('.settings-text-button')!);expect(state.delay).toBe(0);await click(host.querySelector('[aria-label="Maximize settings"]')!);expect(commands.at(-1)).toEqual({type:'settingsWindow',action:'maximize'});expect(host.textContent).not.toContain('Earlier −250 ms');});
it('keeps the exact 72% opacity default and changes it by five points with keyboard input',async()=>{state={...state,settings:settings({opacity:.72})};await act(async()=>render());const slider=host.querySelector<HTMLInputElement>('[aria-label="Background opacity"]')!;expect(slider.value).toBe('72');await act(async()=>slider.dispatchEvent(new KeyboardEvent('keydown',{key:'ArrowRight',bubbles:true,cancelable:true})));expect(state.settings.opacity).toBe(.77);expect(host.querySelector('[aria-label="Background opacity"]')?.getAttribute('value')).toBe('77');});
it('sweeps the sample words against the preview clock as frames advance',async()=>{vi.mocked(performance.now).mockReturnValue(4000);const runFrames=()=>{for(const[id,frame]of[...frames.entries()]){frames.delete(id);frame(4000);}};await act(async()=>runFrames());await act(async()=>runFrames());const words=Array.from(host.querySelectorAll<HTMLElement>('.preview-stage [data-word]'));expect(words).toHaveLength(6);expect(words.slice(0,4).every(word=>word.style.color==='var(--accent)')).toBe(true);expect(words[4].style.color).toBe('var(--fg)');expect(host.querySelector('.preview-stage .ledger-time')?.textContent).toBe('0:16 / 0:54');});

it('keeps optional recognition off, clears entered secrets on submit, and exposes reset/retry controls',async()=>{state={...state,recognition:{enabled:false,consent:false,dailyCap:50,configured:false,capable:true,captureActive:false,reason:'Recognition is off'}};await act(async()=>render());const form=host.querySelector<HTMLInputElement>('[name="host"]')!.form!;for(const[name,value]of Object.entries({host:'identify-eu-west-1.acrcloud.com',key:'synthetic-key',secret:'synthetic-secret'}))form.querySelector<HTMLInputElement>(`[name="${name}"]`)!.value=value;await act(async()=>form.dispatchEvent(new Event('submit',{bubbles:true,cancelable:true})));expect(commands.at(-1)).toEqual({type:'recognitionConfig',host:'identify-eu-west-1.acrcloud.com',key:'synthetic-key',secret:'synthetic-secret'});expect(form.querySelector<HTMLInputElement>('[name="secret"]')!.value).toBe('');expect(JSON.stringify(state)).not.toContain('synthetic-secret');await click(button('Retry lyrics'));expect(commands.at(-1)).toEqual({type:'retryLyrics',videoId:state.videoId});await click(button('Forget match'));expect(commands.at(-1)?.type).toBe('forgetMatch');await click(button('Reset timing'));expect(commands.at(-1)?.type).toBe('resetTiming');});
