import{describe,it,expect,vi,beforeEach,afterEach}from'vitest';
const disk=vi.hoisted(()=>({files:new Map<string,string>()}));
vi.mock('node:fs',()=>({default:{existsSync:(p:string)=>disk.files.has(p),statSync:(p:string)=>({size:disk.files.get(p)?.length??0}),readFileSync:(p:string)=>disk.files.get(p),mkdirSync:()=>{},writeFileSync:(p:string,s:string)=>disk.files.set(p,s),renameSync:(a:string,b:string)=>{disk.files.set(b,disk.files.get(a)!);disk.files.delete(a);}}}));
import{Store}from'../desktop/store';
import{lyric}from'./fixtures';
beforeEach(()=>{disk.files.clear();vi.useFakeTimers();});afterEach(()=>vi.useRealTimers());
describe('bounded local storage with a fake filesystem',()=>{
 it('persists System theme and the new behavior toggles',()=>{const s=new Store('fake-data');Object.assign(s.data.settings,{theme:'system',onlyWhilePlaying:true,launchAtStartup:true,karaoke:false,width:460,fontSize:14});s.flush();expect(new Store('fake-data').data.settings).toMatchObject({theme:'system',onlyWhilePlaying:true,launchAtStartup:true,karaoke:false,width:460,fontSize:14});});
 it('persists a selected overlay theme without altering saved timing',()=>{const s=new Store('fake-data');s.attach('abcdefghijk',lyric);s.setDelay('abcdefghijk',2000);s.data.settings.theme='light';s.data.settings.opacity=.82;s.flush();const restored=new Store('fake-data');expect(restored.data.settings.theme).toBe('light');expect(restored.data.settings.opacity).toBe(.82);expect(restored.delay('abcdefghijk')).toBe(2000);});
 it('persists settings, secret, selected match and per-match delays',()=>{const s=new Store('fake-data');s.data.settings.fontSize=24;s.attach('abcdefghijk',lyric);s.setDelay('abcdefghijk',2000);s.attach('abcdefghijk',{...lyric,id:2});s.setDelay('abcdefghijk',-500);s.attach('abcdefghijk',lyric);expect(s.delay('abcdefghijk')).toBe(2000);s.flush();const restored=new Store('fake-data');expect(restored.data.settings.fontSize).toBe(24);expect(restored.data.secret).toBe(s.data.secret);expect(restored.delay('abcdefghijk')).toBe(2000);});
 it('bounds cache count and size while keeping recent entries',()=>{const s=new Store('fake-data');for(let i=0;i<100;i++){vi.setSystemTime(i);s.cachePut(String(i),[lyric]);}expect(Object.keys(s.data.cache)).toHaveLength(80);expect(s.cacheGet('0')).toBeUndefined();expect(s.cacheGet('99')).toEqual([lyric]);});
 it('bounds video mappings and rejects corrupted local records',()=>{const s=new Store('fake-data');for(let i=0;i<260;i++){vi.setSystemTime(i);s.attach(String(i).padStart(11,'0'),lyric);}expect(Object.keys(s.data.mappings)).toHaveLength(250);s.flush();const file=[...disk.files.keys()][0];disk.files.set(file,JSON.stringify({settings:{fontSize:'bad'},mappings:{abcdefghijk:{record:{...lyric,duration:'bad'}}},secret:'bad',origin:'https://example.com'}));const restored=new Store('fake-data');expect(restored.data.mappings).toEqual({});expect(restored.data.settings.fontSize).toBe(18);expect(restored.data.origin).toBeNull();expect(restored.data.secret).toMatch(/^[a-f0-9]{64}$/);});
});



it('migrates legacy data with an exact backup and does not label it user confirmed',()=>{const before={settings:{theme:'light'},secret:'ab'.repeat(32),origin:'chrome-extension://'+'a'.repeat(32),mappings:{abcdefghijk:{record:lyric,delays:{'1':12000},used:123}},cache:{old:{records:[lyric],used:100}}};const file='fake-data\\data.json'.replace('\\',require('node:path').sep);disk.files.set(file,JSON.stringify(before));const s=new Store('fake-data');expect(s.delay('abcdefghijk')).toBe(12000);expect(s.data.mappings.abcdefghijk.provenance).toBe('legacy-unknown');expect(s.cacheGet('old')).toBeUndefined();s.flush();expect(disk.files.get(file+'.pre-v2.bak')).toBe(JSON.stringify(before));const restored=new Store('fake-data');restored.flush();expect(restored.data.secret).toBe(before.secret);expect(restored.data.origin).toBe(before.origin);expect(disk.files.get(file+'.pre-v2.bak')).toBe(JSON.stringify(before));});
it('protects malformed and unsupported data from later saves',()=>{const file=require('node:path').join('fake-data','data.json');for(const raw of ['{broken',JSON.stringify({schemaVersion:999})]){disk.files.set(file,raw);const s=new Store('fake-data');s.save();expect(()=>s.flush()).toThrow('protected');expect(disk.files.get(file)).toBe(raw);}});
it('does not renew positive or negative fetched freshness on access',()=>{let now=1000;const s=new Store('fake-data',()=>now);s.cachePut('positive',[lyric]);s.cachePut('negative',[]);now+=120000;expect(s.cacheGet('negative')).toEqual([]);expect(s.data.cache.negative.fetchedAt).toBe(1000);now+=200000;expect(s.cacheGet('negative')).toBeUndefined();expect(s.cacheGet('positive')).toEqual([lyric]);now+=8*86400000;expect(s.cacheGet('positive')).toBeUndefined();});
it('keeps absolute manual timing above automatic alignment until reset',()=>{const s=new Store('fake-data');s.attach('abcdefghijk',lyric,'metadata');s.setAutomaticDelay('abcdefghijk',12000,'acr1');expect(s.delay('abcdefghijk')).toBe(12000);s.setDelay('abcdefghijk',-500);s.setAutomaticDelay('abcdefghijk',15000,'acr1');expect(s.delay('abcdefghijk')).toBe(-500);s.resetTiming('abcdefghijk');expect(s.delay('abcdefghijk')).toBe(0);expect(s.data.secret).toHaveLength(64);});
it('persists video-scoped rejection and recognition budgets across restart',()=>{const s=new Store('fake-data');s.attach('abcdefghijk',lyric);s.forget('abcdefghijk');expect(s.rejects('abcdefghijk')).toEqual([1]);expect(s.rejects('lmnopqrstuv')).toEqual([]);expect(s.reserveRecognition('abcdefghijk')).toBe(true);expect(s.reserveRecognition('abcdefghijk')).toBe(true);const restored=new Store('fake-data');expect(restored.reserveRecognition('abcdefghijk')).toBe(false);restored.data.recognition.dailyCap=2;expect(restored.reserveRecognition('lmnopqrstuv')).toBe(false);});
