import React,{useEffect,useRef,useState} from 'react';
import{createRoot}from'react-dom/client';
import type{API,Command,ViewState}from'../../shared/ui';
import './style.css';
import './fonts.css';
import { LedgerOverlay } from './LedgerOverlay';
import { TimingAlignment } from './TimingAlignment';
import { useSettingsNavigation } from './settings-navigation';
declare global{interface Window{lyricglass:API}}
const isSettings=location.hash==='#settings';document.body.className=isSettings?'settings-body':'overlay-body';
function App(){const[state,setState]=useState<ViewState|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState('');
  useEffect(()=>{const off=window.lyricglass.subscribe(setState);void window.lyricglass.getState().then(setState);return off;},[]);
  async function act(c:Command){setError('');setNotice('');try{const r=await window.lyricglass.command(c);if(!r.ok)setError(r.error??'Action failed');else if(c.type==='copyPairing')setNotice('Pairing details copied. Paste them into the extension popup.');}catch{setError('Desktop connection unavailable. Restart LyricGlass.');}}
  if(!state)return <main className="loading">Opening LyricGlass…</main>;
  return isSettings?<Settings state={state} act={act} error={error} notice={notice}/>:<LedgerOverlay state={state} act={act} error={error}/>;
}
type Props={state:ViewState;act:(c:Command)=>Promise<void>;error:string;notice?:string};
function Timing({state:s,act}:Pick<Props,'state'|'act'>){const[value,setValue]=useState(String(s.delay));useEffect(()=>setValue(String(s.delay)),[s.delay,s.videoId]);const disabled=!s.videoId||!s.record;const delay=(v:number)=>void act({type:'delay',videoId:s.videoId!,value:v});return <div className="timing"><button disabled={disabled} onClick={()=>delay(s.delay-250)}>Earlier −250 ms</button><label>Lyric delay (ms)<input aria-label="Lyric delay in milliseconds" type="number" min="-600000" max="600000" step="250" disabled={disabled} value={value} onChange={e=>setValue(e.target.value)} onBlur={()=>{if(value!==''&&Number.isFinite(Number(value)))delay(Number(value));else setValue(String(s.delay));}} onKeyDown={e=>{if(e.key==='Enter')e.currentTarget.blur();}}/></label><button disabled={disabled} onClick={()=>delay(s.delay+250)}>Later +250 ms</button><button disabled={disabled} onClick={()=>delay(0)}>Reset</button></div>;}
function Settings({state:s,act,error,notice}:Props){useSettingsNavigation(s.settingsNavigation);const[query,setQuery]=useState(''),[port,setPort]=useState(String(s.settings.port));useEffect(()=>setPort(String(s.settings.port)),[s.settings.port]);const change=(patch:Command&{type:'settings'})=>void act(patch);
  return <main className="settings"><header className="brand"><span className="brand-mark">≋</span><div><h1>LyricGlass</h1><p>Lyrics above your work.</p></div><span className="local-badge">LOCAL · WINDOWS</span></header>
    <div className="connection"><strong>{s.connection}</strong><span>{s.paired?'Paired extension':'First run · pair your browser below'}</span></div>
    {s.warning&&<p className="alert" role="status">{s.warning}</p>}{error&&<p className="alert" role="alert">{error}</p>}{notice&&<p className="notice" role="status">{notice}</p>}
    <section><div className="section-heading"><span>01</span><h2>Connect your browser</h2></div><p>Load the unpacked extension, copy your pairing details here, then paste them into its popup and choose <strong>Pair with desktop</strong>.</p><div className="row"><button className="primary" onClick={()=>void act({type:'copyPairing'})}>Copy pairing details</button><label>Port<input type="number" min="1024" max="65535" value={port} onChange={e=>setPort(e.target.value)}/></label><button onClick={()=>change({type:'settings',patch:{port:Number(port)}})}>Apply port</button><button onClick={()=>void act({type:'rotatePairing'})}>Reset pairing</button></div><p className="hint">Default: 43821. After a port change or pairing reset, copy and paste new details. One exact extension origin is paired at a time; reset pairing to switch browsers.</p></section>
    <section><div className="section-heading"><span>02</span><h2>Your overlay</h2></div><div className="row"><button className="primary" onClick={()=>void act({type:'lock'})}>{s.settings.locked?'Unlock to move / interact':'Lock · clicks pass through'}</button><button onClick={()=>void act({type:'visibility'})}>{s.settings.visible?'Hide overlay':'Show overlay'}</button><button onClick={()=>void act({type:'resetPosition'})}>Reset position</button></div><div className="appearance"><label>Theme<select value={s.settings.theme} onChange={e=>change({type:'settings',patch:{theme:e.target.value as 'dark'|'light',opacity:e.target.value==='light'?.82:.72}})}><option value="dark">Dark</option><option value="light">Light</option></select></label><label>Background opacity · {Math.round(s.settings.opacity*100)}%<input type="range" min="0" max="1" step=".02" value={s.settings.opacity} onChange={e=>change({type:'settings',patch:{opacity:Number(e.target.value)}})}/></label><label>Text size · {s.settings.fontSize}px<input type="range" min="18" max="42" step="1" value={s.settings.fontSize} onChange={e=>change({type:'settings',patch:{fontSize:Number(e.target.value)}})}/></label><label>Width<select value={s.settings.width} onChange={e=>change({type:'settings',patch:{width:Number(e.target.value)}})}><option value="400">Ledger · 400</option><option value="420">Compact · 420</option><option value="560">Balanced · 560</option><option value="720">Wide · 720</option></select></label><label className="checkbox"><input type="checkbox" checked={s.settings.textOnly} onChange={e=>change({type:'settings',patch:{textOnly:e.target.checked}})}/>Text only with shadow</label></div><p className="hint">{s.shortcuts.join('  •  ')}. The tray always provides recovery controls.</p></section>
    <section id="match-section"><div className="section-heading"><span>03</span><h2>Choose lyric match & timing</h2></div><div className="now-playing"><strong>{s.title}</strong><p>{s.status}</p>{s.record&&<small>Selected: {s.record.artistName} — {s.record.trackName} · {s.record.albumName==='Local LRC import'?'Imported LRC':`LRCLIB #${s.record.id}`}</small>}</div>
    <TimingAlignment state={s} act={act} error={error}/><p className="hint">Choose a result below to use its lyrics. Check the artist, recording and duration; prefer a Synced result. Search or import an LRC if none is right.</p><form className="row search" onSubmit={e=>{e.preventDefault();void act({type:'search',videoId:s.videoId!,query});}}><input id="match-search" aria-label="Search title and artist" placeholder="Search title and artist…" maxLength={300} value={query} onChange={e=>setQuery(e.target.value)}/><button className="primary" disabled={!s.videoId||!query.trim()}>Search LRCLIB</button><button type="button" disabled={!s.videoId} onClick={()=>void act({type:'import',videoId:s.videoId!})}>Import .lrc</button></form>
    {s.candidates.length>0&&<div className="candidates">{s.candidates.map(r=><button key={r.id} className={`candidate ${s.record?.id===r.id?'selected':''}`} onClick={()=>void act({type:'select',videoId:s.videoId!,id:r.id})}><span><strong>{r.trackName}</strong><small>{r.artistName} · {r.albumName}</small></span><span>{Math.floor(r.duration/60)}:{String(Math.round(r.duration%60)).padStart(2,'0')}<small>{r.timingWarning?'Timing mismatch':r.instrumental?'Instrumental':r.hasSynced?'Synced':'Untimed'}</small><small className="candidate-action">{s.record?.id===r.id?'Selected':'Use lyrics'}</small></span></button>)}</div>}
    <Timing state={s} act={act}/><p className="hint">Positive delay means lyrics appear later. With +2000 ms, a 10-second line appears at video time 12 seconds. Saved per video and chosen match.</p>
    {s.record&&!s.record.hasSynced&&s.plain&&<details><summary>Untimed lyrics · manual reading</summary><pre className="plain-lyrics">{s.plain}</pre></details>}</section>
    <footer><button className="link" onClick={()=>void act({type:'providerLink'})}>Lyrics provided by LRCLIB ↗</button><p>No audio capture. No accounts. Your settings, matches and imported lyrics stay on this computer.</p></footer>
  </main>;
}
createRoot(document.getElementById('root')!).render(<App/>);



