import type { Settings } from './settings';
import {recordTimingWarning,type RecordLyrics} from './lyrics';
import type { LedgerState } from './ledger';
export type LyricSummary=Omit<RecordLyrics,'plainLyrics'|'syncedLyrics'>&{hasSynced:boolean;timingWarning?:string};
export function summarize(r:RecordLyrics):LyricSummary{const{plainLyrics:_plain,syncedLyrics,...summary}=r;return{...summary,hasSynced:!r.instrumental&&!!syncedLyrics,timingWarning:r.instrumental?undefined:recordTimingWarning(r)};}
export interface TimingLines {videoId:string;recordId:number;lines:{index:number;time:number;text:string}[]}
export interface SettingsNavigation {section:'general'|'match';request:number}
export interface ViewState {settings:Settings;connection:string;warning:string;videoId:string|null;title:string;artist:string;status:string;previous:string;current:string;next:string;plain:string|null;delay:number;record:LyricSummary|null;candidates:LyricSummary[];paired:boolean;shortcuts:string[];ledger:LedgerState;settingsNavigation?:SettingsNavigation;timingWarning?:string;resolvedTheme?:'dark'|'light';connectionBrowser?:string;settingsMaximized?:boolean}
export interface RecognitionState {enabled:boolean;consent:boolean;dailyCap:number;configured:boolean;capable:boolean;captureActive:boolean;reason:string}
export interface ViewState {recognition?:RecognitionState;diagnostics?:{at:number;stage:string;requests:number;duration?:number|null;outcome?:string;candidates?:{id:number;score:number;reasons:string[];conflicts:string[];timing:string}[]}[];matchProvenance?:string}
export type Command = {type:'retryLyrics'|'forgetMatch'|'resetTiming';videoId:string}|{type:'recognitionConfig';host:string;key:string;secret:string}|{type:'recognitionRemove'}|{type:'recognitionSettings';enabled:boolean;consent:boolean;dailyCap:number}|{type:'exportDiagnostics'}|{type:'settings';patch:Partial<Settings>}|{type:'lock'}|{type:'visibility'}|{type:'openSettings';section?:'match'}|{type:'resetPosition'}|{type:'copyPairing'}|{type:'rotatePairing'}|{type:'search';videoId:string;query:string}|{type:'select';videoId:string;id:number}|{type:'import';videoId:string}|{type:'delay';videoId:string;value:number}|{type:'align';videoId:string;recordId:number;index:number}|{type:'providerLink'}|{type:'height';value:number}|{type:'settingsWindow';action:'minimize'|'maximize'|'close'}|{type:'drag';phase:'start'|'move'|'end';x:number;y:number};
export interface API { getState():Promise<ViewState>;getTimingLines(videoId:string):Promise<TimingLines>;command(command:Command):Promise<{ok:boolean;error?:string}>;subscribe(callback:(state:ViewState)=>void):()=>void }
